### ISSUE TITLE
NAs in harmonics

### ISSUE THREAD

**Issue by maRce10** [tatters/soundgen#1]
Hi

In many cases I got NAs for the "harmonics" parameter returned by analyze(). Can this be interpreted as no energy in the upper harmonics?

thanks

**Comment by tatters** [comment]
Hi,
Sorry for the super-slow response, I hardly ever check github directly - please email me to rty.anik@rambler.ru for further queries. The energy in harmonics can only be estimated if there is a pitch candidate for the current frame (ie if the frame is considered to be voiced). I'm guessing the NAs are coming from frames in which pitch could not be estimated. A reproducible example would help!
Best regards,
Andrey

**Comment by maRce10** [comment]
Thanks,

here it is. Is not a great example but it's where I had the issue. There is a bird song there.

```
library(NatureSounds)
library(soundgen)

data("Phae.long1")

clp <- cutw(Phae.long1, f = 22050, from = 1.1693549, to = 1.1893549)

analyze(x = as.numeric(clp), samplingRate = 22050, windowLength = 5, plot = T,  nFormants = 3)
```
as you can see the 'harmonics' column contains only NAs.

**Comment by tatters** [comment]
Yes, in this case you also get nothing but NAs for pitch, and without a pitch estimate the energy in harmonics cannot be estimated, either. Here's a slightly modified code for the same example that shows some pitch estimates (not very good, though) and non-NA values of "harmonics" for the voiced parts:

`clp <- seewave::cutw(Phae.long1, f = 22050, from = 1.15, to = 1.4) `
`a = analyze(x = as.numeric(clp), 
        pitchCeiling = 4500, priorMean = HzToSemitones(3000), priorSD = 12,  
       domThres = .4,
        samplingRate = 22050, 
        windowLength = 5, overlap = 0,
        plot = T,  nFormants = 3)`
`a$harmonics`
