### ISSUE TITLE
Error in maxPoints[1] < ls :    comparison (3) is possible only for atomic and list types

### ISSUE THREAD

**Issue by hariskr** [tatters/soundgen#3]
I am having an issue with the following code:

s11 = load.wave("StarWars3.wav")
a2 = analyze(s11, windowLength = 25, overlap = 20, SPL_measured = 40, samplingRate = 22050)

The error message is:
Error in maxPoints[1] < ls : 
  comparison (3) is possible only for atomic and list types

The source of the file is:
https://www2.cs.uic.edu/~i101/SoundFiles/StarWars3.wav

**Comment by tatters** [comment]
Different packages import audio into R in different formats. audio::load.wave produces an object of class "audioSample", which is currently not supported by soundgen. The solution is simple: read the file directly with analyze("StarWars3.wav", windowLength = ... etc ...). 
Alternatively, you can import it with tuneR::readWave and then work with the raw waveform as a numeric vector;
s11 = tuneR::readWave("StarWars3.wav")
s11_vector = s11@left
s11_samplingRate = s11@samp.rate

**Comment by hariskr** [comment]
I tried that first and also got a problem - please fine my code and output below.

sound4 = readWave("StarWars3.wav")
sound4
a4 = analyze(sound4, windowLength = 50)

Output:
> sound4 = readWave("StarWars3.wav")
> sound4

Wave Object
	Number of Samples:      66150
	Duration (seconds):     3
	Samplingrate (Hertz):   22050
	Channels (Mono/Stereo): Mono
	PCM (integer format):   TRUE
	Bit (8/16/24/32/64):    16 

> a4 = analyze(sound4, windowLength = 50)
Error in analyze(sound4, windowLength = 50) : 
  Input not recognized: must be a numeric vector or wav/mp3 file

Could you please advice why input is not recognized? Many thanks.

**Comment by tatters** [comment]
"Input not recognized: must be a numeric vector or wav/mp3 file" means that the input can be a simple numeric vector or path to file. So, as I mentioned before, you can write either `analyze("StarWars3.wav")` or `sound4 = readWave("StarWars3.wav"); analyze(sound4@left, samplingRate = sound4@samp.rate)`. I'm currently updating soundgen, and the next release will also support the "Wave" format returned by `readWave`.
