### ISSUE TITLE
Object does not exist after upload

### ISSUE THREAD

**Issue by hariskr** [tatters/soundgen#5]
The following object does not seem to exist after employing the analyze() function on it. 

C320 = analyze("Les Dennis_01.mp3") 
exists('c320')

returns FALSE

whereas 
c321 = analyze("Les Dennis_02.mp3")

returns TRUE

Why is the first false and second true? seems arbitrary and I would like the the first to be true if possible. The links for the two are below:

https://www.dropbox.com/s/tfbclyexsjgjtov/Les%20Dennis_01.mp3?dl=0

https://www.dropbox.com/s/440n3wp6854802g/Les%20Dennis_02.mp3?dl=0

**Comment by tatters** [comment]
Can you please update from github and try again? There was a little glitch with mp3 inputs - I'm in the process of a major update to soundgen 2.0, and the developmental version is a bit unstable.

**Comment by tatters** [comment]
I'm marking the issue as resolved. Please contact me if the problem persists.
