### ISSUE TITLE
Any possibility of typing in (not dragging) exact pitch?

### ISSUE THREAD

**Issue by kirkmarkarian** [tatters/soundgen#6]
Any possibility of typing in (not dragging) exact pitch?  This makes an excellent vocal sound generator for a variety of TTS and singing synthesis sounds.  Would be wonderful to be able to pitch it precisely!

**Comment by tatters** [comment]
Not really sure what you mean... You can take a pitch contour of a real long utterance (as a vector of arbitrary length) and feed it into soundgen. In fact, even NAs are not a problem (ie unvoiced pauses). Example: 
`soundgen(sylLen = 2000, pitch = c(rnorm(10, 200, 10), NA, NA, NA, rnorm(10, 400, 50)), plot = T, play = T)`

**Comment by kirkmarkarian** [comment]
For those of us who are non-programmers, not familiar with the R scripting language (such as myself).  I stumbled across your software online and have found it pretty interesting to use as a sound-source.  Being a fan of singing synthesis, and not having to use samples of other people's voices (UTAU, etc.), soundgen seems to fit a niche for what I'm actually creating.

In the case of typing in pitch, say I wanted 263.63 Hz (middle C), I could drag the points in the graph area, but the closest I was able to get was 261 Hz.  I technically could then generate this sample, drag it into an editor, and then re-pitch it to be the pitch that I'm looking for, but typing in the pitch would save a step.

![Screen Shot 2021-09-18 at 8 48 57 AM](https://user-images.githubusercontent.com/38725630/133894689-eef55295-fcb3-40ad-a480-67a37b7465d2.jpg)

Please keep in mind, I do not program (nor do I understand the vernacular you're using, as I do not study vocal sounds as a science), but I do enjoy the form of synthesis soundgen is creating.  Very accurate 'human'-sounding vocal pieces.

**Comment by tatters** [comment]
Oh, right, I see! Well, the app you are using is more like a demo, really - enough to get a feel for the method, but not for using it "seriously" (for science / music / whatever). Soundgen is an R package, so to make full use of it, it is necessary to use R. You don't need to program anything much, but that's just the language in which these functions are implemented. As a minimum, you'd have to specify the value of different arguments (like "pitch") and save the output. I suggest you look at the vignette on sound synthesis, for a start:  https://cogsci.se/soundgen/sound_generation.html   And https://cogsci.se/soundgen/demos.html  for general info. Hope that helps! Cheers, Andrey
