### ISSUE TITLE
I'll say it again - sure would be nice to have these additions to the online version :)

### ISSUE THREAD

**Issue by NeuroNoNeuro** [tatters/soundgen#7]
Please?  Such beautiful synthesized vocal sounds for abstract music - please may we have the capability to tune the pitch in finer detail?  Please?

**Comment by tatters** [comment]
Well, actually it is already possible to type in pitch values in soundgen_app() - see the attached video. If that's not what you have in mind, can you specify what the desired feature should look like? / Andrey

https://user-images.githubusercontent.com/29304757/153718403-e10e2452-3a3b-4ede-991e-a2cadb6b6291.mp4

**Comment by tatters** [comment]
Note: if the video doesn't play in the browser, you can download it and play locally

**Comment by NeuroNoNeuro** [comment]
Oh!  That'll work just fine - thank you for clarifying that for me :)
